# Generated by Django 2.0.2 on 2018-03-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'db_table': 'mdm_merchandize_category',
                'permissions': (('view_mdm_merchandize_category', 'Can view mdm merchandize categories'), ('edit_mdm_merchandize_category', 'Can edit mdm merchandize categories')),
                'default_permissions': ('add_mdm_merchandize', 'change_mdm_merchandize', 'delete_mdm_merchandize'),
            },
        ),
    ]
