# Generated by Django 2.0.2 on 2018-03-31 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('code', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mdm_merchandizes', to='merchandize.Category')),
            ],
            options={
                'db_table': 'mdm_merchandize',
                'permissions': (('view_mdm_merchandize', 'Can view mdm merchandizes'), ('edit_mdm_merchandize', 'Can edit mdm merchandizes'), ('view_properties_mdm_merchandize', 'Can view mdm merchandizes properties'), ('edit_properties_mdm merchandizes', 'Can edit mdm merchandizes properties')),
                'default_permissions': ('add_mdm_merchandize', 'change_mdm_merchandize', 'delete_mdm_merchandize'),
            },
        ),
    ]
