# Generated by Django 2.0.2 on 2018-03-31 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandize', '0003_auto_20180331_1355'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attribute',
            table='mdm_merchandize_attribute',
        ),
        migrations.AlterModelTable(
            name='attributechoicevalue',
            table='mdm_merchandize_attribute_choice_value',
        ),
    ]
