# Generated by Django 2.0.4 on 2018-04-26 18:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchandise', '0004_auto_20180427_0135'),
        ('customer_store', '0003_auto_20180427_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('merchandise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='merchandise.MerchandiseMasterItem')),
                ('store_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='product_items', to='customer_store.CustomerStoreType')),
                ('uom', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='product_items', to='merchandise.UnitOfMeasurement')),
            ],
            options={
                'db_table': 'product_item',
            },
        ),
    ]
