# Generated by Django 2.0.4 on 2018-05-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_store', '0007_auto_20180506_1851'),
        ('product', '0002_productitem_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='store_type',
        ),
        migrations.AddField(
            model_name='productitem',
            name='store_type',
            field=models.ManyToManyField(related_name='product_items', to='customer_store.CustomerStoreType'),
        ),
    ]
