# Generated by Django 2.0.4 on 2018-05-16 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180507_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('abspath', models.CharField(max_length=256)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.ProductItem')),
            ],
            options={
                'db_table': 'product_item_image',
                'permissions': (('view_productitemimage', 'Can view product item images'),),
            },
        ),
    ]
