#!/bin/sh

CURRENT_PATH=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
APP_PATH=$CURRENT_PATH/app

if ! grep -qr "alias horizon=$CURRENT_PATH/horizon" ~/.bash_profile
    then
        echo "alias horizon=$CURRENT_PATH/horizon" >> ~/.bash_profile
        source ~/.bash_profile
fi

if [ -z $1 ] || [ $1 == help ]
then
    echo "horizon help"
    echo "horizon init"
    echo "horizon ..."
elif [ $1 == init ]
then
    echo 1
    # Install Saleor
fi
