# Generated by Django 2.0.2 on 2018-04-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_extension', '0003_auto_20180408_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteproduct',
            name='favorite_name',
            field=models.CharField(default='default', max_length=512),
            preserve_default=False,
        ),
    ]
