# Generated by Django 2.0.4 on 2018-04-26 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'route',
                'permissions': (('view_route', 'Can view routes'),),
            },
        ),
        migrations.CreateModel(
            name='RouteActivity',
            fields=[
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('schedule_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHE', 'Scheduled'), ('FUTU', 'Future'), ('EXEC', 'Executed')], default='SCHE', max_length=4)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_route_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'route_activity',
            },
        ),
        migrations.CreateModel(
            name='RouteActivityTask',
            fields=[
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_tasks', to='routing.RouteActivity')),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'route_activity_task',
            },
        ),
        migrations.CreateModel(
            name='RouteCustomerStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing.Route')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_store.CustomerStore')),
            ],
            options={
                'db_table': 'route_customer',
            },
        ),
        migrations.AddField(
            model_name='routeactivity',
            name='route_stores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing.RouteCustomerStore'),
        ),
        migrations.AddField(
            model_name='routeactivity',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_route_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='route',
            name='stores',
            field=models.ManyToManyField(through='routing.RouteCustomerStore', to='customer_store.CustomerStore'),
        ),
    ]
