# Generated by Django 2.0.4 on 2018-04-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_route_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='route',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
