# Generated by Django 2.0.4 on 2018-05-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0003_routeactivitytask_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routeactivitytask',
            name='status',
        ),
        migrations.AddField(
            model_name='routecustomerstore',
            name='status',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
