# Generated by Django 2.0.4 on 2018-05-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0007_routecustomerstore_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routecustomerstore',
            name='status',
            field=models.CharField(choices=[('CHECKIN', 'Check-in'), ('SURVEY', 'Survey'), ('PREORDER', 'PreOrder'), ('PAYMENT', 'Payment'), ('DONOTHING', 'Do-nothing')], default='SURVEY', max_length=10, null=True),
        ),
    ]
