# Generated by Django 2.0.4 on 2018-05-17 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0003_auto_20180517_0117'),
        ('routing', '0010_remove_route_stores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routetaskquestionaire',
            name='questions',
        ),
        migrations.AddField(
            model_name='routetaskquestionaire',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='task_questionaire', to='questionaire.QuestionaireAnswer'),
            preserve_default=False,
        ),
    ]
