# Generated by Django 2.0.4 on 2018-04-26 16:59

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchandiseMasterItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('price', django_prices.models.MoneyField(currency='THB', decimal_places=2, max_digits=12)),
                ('available_on', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('attributes', django.contrib.postgres.fields.hstore.HStoreField(default={})),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchandises_of_category', to='merchandise.MerchandiseCategory')),
            ],
            options={
                'db_table': 'merchandise_master_item',
                'permissions': (('view_merchandise', 'Can view merchandises'), ('edit_merchandise', 'Can edit merchandises'), ('view_properties', 'Can view merchandise properties'), ('edit_properties', 'Can edit merchandise properties')),
            },
        ),
        migrations.RemoveField(
            model_name='merchandise',
            name='category',
        ),
        migrations.RemoveField(
            model_name='merchandise',
            name='merchandise_type',
        ),
        migrations.RemoveField(
            model_name='merchandisetype',
            name='merchandise_attributes',
        ),
        migrations.RemoveField(
            model_name='merchandisetype',
            name='variant_attributes',
        ),
        migrations.AlterField(
            model_name='collection',
            name='merchandises',
            field=models.ManyToManyField(blank=True, related_name='collections', to='merchandise.MerchandiseMasterItem'),
        ),
        migrations.AlterField(
            model_name='merchandiseimage',
            name='merchandise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='merchandise.MerchandiseMasterItem'),
        ),
        migrations.AlterField(
            model_name='merchandisevariant',
            name='merchandise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='merchandise.MerchandiseMasterItem'),
        ),
        migrations.DeleteModel(
            name='Merchandise',
        ),
        migrations.DeleteModel(
            name='MerchandiseType',
        ),
    ]
