# Generated by Django 2.0.4 on 2018-04-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0001_auto_20180423_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='code',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
