# Generated by Django 2.0.4 on 2018-04-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_auto_20180426_2359'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attributechoicevalue',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='attributechoicevalue',
            name='attribute',
        ),
        migrations.DeleteModel(
            name='AttributeChoiceValue',
        ),
        migrations.DeleteModel(
            name='MerchandiseAttribute',
        ),
    ]
