# Generated by Django 2.0.4 on 2018-04-26 18:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0003_auto_20180427_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'unit_of_conversion',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'unit_of_measurement',
            },
        ),
        migrations.RemoveField(
            model_name='merchandisemasteritem',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='merchandisevariant',
            name='attributes',
        ),
        migrations.AlterField(
            model_name='merchandisevariant',
            name='sku',
            field=models.CharField(default=uuid.uuid1, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='unitofmeasurement',
            name='merchandise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uoms', to='merchandise.MerchandiseMasterItem'),
        ),
        migrations.AddField(
            model_name='unitofmeasurement',
            name='unit_conversions',
            field=models.ManyToManyField(related_name='uoms', to='merchandise.UnitOfConversion'),
        ),
    ]
