# Generated by Django 2.0.4 on 2018-04-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0004_auto_20180427_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandisemasteritem',
            name='price',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='merchandisevariant',
            name='price_override',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cost_price',
            field=models.FloatField(default=None, null=True),
        ),
    ]
