# Generated by Django 2.0.4 on 2018-04-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0005_auto_20180429_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofconversion',
            name='factor',
            field=models.FloatField(default=None, null=True),
        ),
    ]
