# Generated by Django 2.0.4 on 2018-05-06 23:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0006_unitofconversion_factor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchandisecategory',
            options={'ordering': ('slug',), 'permissions': (('view_merchandise_category', 'Can view merchandise categories'),)},
        ),
        migrations.AlterField(
            model_name='merchandisevariant',
            name='sku',
            field=models.CharField(default=uuid.uuid1, max_length=40, unique=True),
        ),
    ]
