# Generated by Django 2.0.4 on 2018-05-16 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0007_auto_20180506_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandiseimage',
            name='merchandise',
        ),
        migrations.RemoveField(
            model_name='merchandisevariant',
            name='images',
        ),
        migrations.RemoveField(
            model_name='merchandisevariant',
            name='merchandise',
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='stock',
            name='location',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='variantimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='variantimage',
            name='variant',
        ),
        migrations.DeleteModel(
            name='MerchandiseImage',
        ),
        migrations.DeleteModel(
            name='MerchandiseVariant',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='StockLocation',
        ),
        migrations.DeleteModel(
            name='VariantImage',
        ),
    ]
