# Generated by Django 2.0 on 2018-06-21 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'merchandise_item_category',
                'ordering': ('code',),
                'permissions': (('view_item_category', 'Can view item categories'),),
            },
        ),
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=512)),
                ('description', models.CharField(blank=True, max_length=4096, null=True)),
            ],
            options={
                'db_table': 'merchandise_item_master',
                'ordering': ('code',),
                'permissions': (('view_item_master', 'Can view master items'),),
            },
        ),
        migrations.CreateModel(
            name='ItemSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_children', to='merchandise.ItemCategory')),
            ],
            options={
                'db_table': 'merchandise_item_sub_category',
                'ordering': ('code',),
                'permissions': (('view_item_sub_category', 'Can view item sub-categories'),),
            },
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_item_masters', to='merchandise.ItemSubCategory'),
        ),
    ]
