# Generated by Django 2.0 on 2018-06-21 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUnitOfConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('factor', models.FloatField(default=None, null=True)),
            ],
            options={
                'db_table': 'merchandise_unit_of_conversion',
            },
        ),
        migrations.CreateModel(
            name='ItemUnitOfMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_code', models.CharField(max_length=50)),
                ('package_name', models.CharField(max_length=50)),
                ('item_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uoms', to='merchandise.ItemMaster')),
                ('unit_conversions', models.ManyToManyField(related_name='uoms', to='merchandise.ItemUnitOfConversion')),
            ],
            options={
                'db_table': 'merchandise_unit_of_measurement',
            },
        ),
    ]
