# Generated by Django 2.0 on 2018-06-21 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_itemunitofconversion_itemunitofmeasurement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemunitofconversion',
            options={'ordering': ('code',), 'permissions': (('view_unit_of_conversion', 'Can view unit of conversions'),)},
        ),
        migrations.AlterModelOptions(
            name='itemunitofmeasurement',
            options={'ordering': ('package_code',), 'permissions': (('view_unit_of_measurement', 'Can view unit of measurements'),)},
        ),
    ]
