# Generated by Django 2.0.4 on 2018-04-28 18:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArInvoice',
            fields=[
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ar_invoice',
            },
        ),
        migrations.CreateModel(
            name='ArReceive',
            fields=[
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ar_receive', to='financial.ArInvoice')),
            ],
            options={
                'db_table': 'ar_receive',
            },
        ),
    ]
