# Generated by Django 2.0.4 on 2018-05-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_arinvoice_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='arinvoice',
            name='status',
            field=models.CharField(choices=[('Raised', 'Raised'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered'), ('Paid', 'Paid'), ('Cancel', 'Cancel')], default='Raised', max_length=20),
        ),
    ]
