# Generated by Django 2.0.4 on 2018-04-28 18:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Raised', 'Raised'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered'), ('Paid', 'Paid'), ('Cancel', 'Cancel')], default='Raised', max_length=10)),
                ('delivery_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'purchase_order',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleDeliveryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'sale_delivery_detail',
            },
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Raised', 'Raised'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered'), ('Paid', 'Paid'), ('Cancel', 'Cancel')], default='Raised', max_length=10)),
                ('delivery_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'sale_order',
            },
        ),
        migrations.CreateModel(
            name='SaleOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='product.ProductItem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='order.SaleOrder')),
            ],
            options={
                'db_table': 'sale_order_detail',
            },
        ),
    ]
