# Generated by Django 2.0.4 on 2018-04-28 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0005_auto_20180423_2357'),
        ('routing', '0002_routetaskorder_routetaskquestionaire'),
        ('order', '0001_initial'),
        ('vendor', '0002_purchaseitem'),
        ('customer_store', '0004_auto_20180427_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='routing.RouteTaskOrder'),
        ),
        migrations.AddField(
            model_name='saledeliverydetail',
            name='company_address',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='common.Address'),
        ),
        migrations.AddField(
            model_name='saledeliverydetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_details', to='order.SaleOrder'),
        ),
        migrations.AddField(
            model_name='saledeliverydetail',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_details', to='customer_store.CustomerStore'),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='vendor.PurchaseItem'),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='order.PurchaseOrder'),
        ),
    ]
