# Generated by Django 2.0.4 on 2018-04-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanname',
            name='middle',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
