# Generated by Django 2.0.4 on 2018-04-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20180423_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanname',
            name='middle',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
