# Generated by Django 2.0.4 on 2018-04-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20180423_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='line2',
            field=models.TextField(null=True),
        ),
    ]
