# Generated by Django 2.0.4 on 2018-04-26 15:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0005_auto_20180423_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStore',
            fields=[
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=512, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_store',
                'permissions': (('view_customerstore', 'Can view customer stores'),),
            },
        ),
        migrations.CreateModel(
            name='CustomerStoreAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Address')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customer_store_address',
                'permissions': (('view_customerstoreaddress', 'Can view customer store addresses'),),
            },
            bases=('common.address', models.Model),
        ),
        migrations.CreateModel(
            name='CustomerStoreContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=256)),
                ('customer_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_store_contacts', to='customer_store.CustomerStore')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_store_contacts', to='common.HumanName')),
            ],
            options={
                'db_table': 'customer_store_contact',
                'permissions': (('view_customerstorecontact', 'Can view customer store contacts'),),
            },
        ),
        migrations.CreateModel(
            name='CustomerStoreImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('customer_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_store_images', to='customer_store.CustomerStore')),
            ],
            options={
                'db_table': 'customer_store_image',
                'permissions': (('view_customerstoreimage', 'Can view customer stores images'),),
            },
        ),
        migrations.CreateModel(
            name='CustomerStoreType',
            fields=[
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=256)),
                ('name', models.TextField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='customer_store.CustomerStoreType')),
            ],
            options={
                'db_table': 'customer_store_type',
                'permissions': (('view_customerstoretype', 'Can view customer store types'),),
            },
        ),
        migrations.AddField(
            model_name='customerstore',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_store', to='customer_store.CustomerStoreAddress'),
        ),
        migrations.AddField(
            model_name='customerstore',
            name='owner',
            field=models.ManyToManyField(related_name='customer_stores', to='common.HumanName'),
        ),
        migrations.AddField(
            model_name='customerstore',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_stores', to='customer_store.CustomerStoreType'),
        ),
    ]
