# Generated by Django 2.0.4 on 2018-04-22 20:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=512, null=True)),
                ('description', models.TextField(null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_store', to='common.Address')),
                ('owner', models.ManyToManyField(related_name='customer_stores', to='common.HumanName')),
            ],
            options={
                'db_table': 'customer_store',
                'permissions': (('view_customerstore', 'Can view customer stores'),),
            },
        ),
        migrations.CreateModel(
            name='CustomerStoreContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=256)),
                ('customer_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_store_contacts', to='customer_store.CustomerStore')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_store_contacts', to='common.HumanName')),
            ],
            options={
                'db_table': 'customer_store_contact',
                'permissions': (('view_customerstorecontact', 'Can view customer store contacts'),),
            },
        ),
        migrations.CreateModel(
            name='CustomerStoreImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='customer_store_images')),
                ('customer_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='customer_store.CustomerStore')),
            ],
            options={
                'db_table': 'customer_store_image',
                'permissions': (('view_customerstoreimage', 'Can view customer stores images'),),
            },
        ),
        migrations.CreateModel(
            name='CustomerStoreType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=256)),
                ('name', models.TextField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='customer_store.CustomerStoreType')),
            ],
            options={
                'db_table': 'customer_store_type',
                'permissions': (('view_customerstoretype', 'Can view customer store types'),),
            },
        ),
        migrations.AddField(
            model_name='customerstore',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_stores', to='customer_store.CustomerStoreType'),
        ),
    ]
