# Generated by Django 2.0.4 on 2018-04-22 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
        ('customer_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerstore',
            name='route',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customer_store', to='routing.Route'),
            preserve_default=False,
        ),
    ]
