# Generated by Django 2.0.4 on 2018-04-26 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_store', '0002_auto_20180426_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstore',
            name='grade',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='customer_store.CustomerStoreGrade'),
        ),
    ]
