# Generated by Django 2.0.4 on 2018-04-22 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('customer_store', '0002_customerstore_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStoreAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Address')),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customer_store_address',
                'permissions': (('view_customerstoreaddress', 'Can view customer store addresses'),),
            },
            bases=('common.address',),
        ),
        migrations.AlterField(
            model_name='customerstore',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_store', to='customer_store.CustomerStoreAddress'),
        ),
    ]
