# Generated by Django 2.0.4 on 2018-04-26 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_store', '0003_auto_20180427_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstoregrade',
            name='higher_grade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='higher', to='customer_store.CustomerStoreGrade'),
        ),
        migrations.AlterField(
            model_name='customerstoregrade',
            name='lower_grade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='lower', to='customer_store.CustomerStoreGrade'),
        ),
    ]
