# Generated by Django 2.0.4 on 2018-05-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_store', '0004_auto_20180427_0224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerstore',
            old_name='owner',
            new_name='owners',
        ),
        migrations.RemoveField(
            model_name='customerstorecontact',
            name='customer_store',
        ),
    ]
