# Generated by Django 2.0.4 on 2018-04-22 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_store', '0004_auto_20180423_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstore',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_store', to='routing.Route'),
        ),
    ]
