# Generated by Django 2.0.4 on 2018-04-23 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_store', '0005_auto_20180423_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstore',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerstore',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_store', to='routing.Route'),
        ),
    ]
