# Generated by Django 2.0.4 on 2018-05-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_store', '0006_customerstorecontact_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerstoreimage',
            name='image',
        ),
        migrations.AddField(
            model_name='customerstoreimage',
            name='abspath',
            field=models.CharField(default='/Users/thanut/Desktop/other/siteline/pmart-g2/horizont-portal/images/images/aHR0cHM6Ly9zLmlzYW5vb2suY29tL3ZpLzAvdWQvNC8xNy9qcGcvMTk2LzM5MzQzMTEuanBn.jpg', max_length=256),
            preserve_default=False,
        ),
    ]
