# Generated by Django 2.0.4 on 2018-04-23 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_store', '0007_auto_20180423_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstoreimage',
            name='customer_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_store_images', to='customer_store.CustomerStore'),
        ),
    ]
