# Generated by Django 2.0.4 on 2018-04-28 18:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_store', '0004_auto_20180427_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionaireAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.NullBooleanField(default=None)),
            ],
            options={
                'db_table': 'questionaire_answer',
            },
        ),
        migrations.CreateModel(
            name='QuestionaireTemplate',
            fields=[
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('store_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionaires', to='customer_store.CustomerStoreType')),
            ],
            options={
                'db_table': 'questionaire_template',
            },
        ),
        migrations.AddField(
            model_name='questionaireanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionaire.QuestionaireTemplate'),
        ),
    ]
