# Generated by Django 2.0.4 on 2018-05-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_store', '0007_auto_20180506_1851'),
        ('questionaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionairetemplate',
            name='store_type',
        ),
        migrations.AddField(
            model_name='questionairetemplate',
            name='store_type',
            field=models.ManyToManyField(related_name='questionaires', to='customer_store.CustomerStoreType'),
        ),
    ]
