# Generated by Django 2.0.4 on 2018-05-17 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_store', '0007_auto_20180506_1851'),
        ('questionaire', '0002_auto_20180507_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaireanswer',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='customer_store.CustomerStore'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionaireanswer',
            name='answer',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
