# Generated by Django 2.0.2 on 2018-04-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_extension', '0002_auto_20180408_0146'),
        ('social_django', '0008_partial_timestamp'),
        ('order', '0038_auto_20180228_0451'),
        ('impersonate', '0001_initial'),
        ('cart', '0006_auto_20180221_0825'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
